* quake-mode
  Demo:

  [[http://www.youtube.com/watch?v=ZithVlRsjKo]]

  Minor mode providing Quake/Unreal-style killing sprees in Emacs.
  
* Installation
Add the following to your `.emacs` file to enable the use of `quake-mode`:

#+BEGIN_SRC
(add-to-list 'load-path "~/.emacs.d/quake-mode")
(load "quake-mode.el")
#+END_SRC

The above assumes that you saved the project files in a folder `quake-mode`, inside
the `.emacs.d` directory.
** Usage:
   Use
    #+BEGIN_SRC 
M-x: quake-mode
     #+END_SRC
   to toggle the mode on and off
** Fragging
   Currently the following functions count as a frag:
       #+BEGIN_SRC 
  (kill-word)
  (backward-kill-word)
  (kill-comment)
  (kill-line)
  (kill-visual-line)
  (kill-whole-line)
  (kill-rectangle)
  (kill-region)
  (kill-buffer)
     #+END_SRC
   ... and more probably
** Customization
*** Defining a frag
   You can enable other functions to count as frags like this:
       #+BEGIN_SRC lisp
;; kill-sexp will now count as a frag
  (quake/define-frag kill-sexp) 
     #+END_SRC
*** Defining an event
    You can choose how many kills certain events require like this:
   #+BEGIN_SRC 
;; at 8 kills, announce MEGE KILL and play the megakill.wav sound
(quake/define-spree-event 8  "MEGA KILL" "megakill.wav")
   #+END_SRC
** Sounds:
   The standard announcer sounds are all available.
  
** TODO Todo List
*** Better Gamification
Counting every `kill' as a frag can be annoying, killing three blank lines of text should really not be considered a triple kill. Perhaps the size of the text killed should determin the frag.
*** Team Killer and Humiliation
Maybe after a lot of consecutive undos you are considered a team killer or humiliated
*** VC / magit integration
commits, pushes, reverts, who knows
*** Better Sounds
I just found these on some forum with no attached license, need something offical
*** Better Customization
Use emacs customize, groups, and what not


    
